# Nixpacks configuration for observability service
# This file is at the root to ensure Railway picks it up

[phases.setup]
nixPkgs = ["bun"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd observability && bun install"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd observability && bun run typecheck || true"]

[start]
cmd = "cd observability && bun start"

[variables]
PORT = "8000"