# Railway configuration for tools monorepo
# Each service should have its own nixpacks.toml in its directory

[[services]]
name = "observability"
# Railway will use the nixpacks.toml found in the observability directory