[build]
builder = "NIXPACKS"
nixpacksConfigPath = "observability/nixpacks.toml"
watchPaths = ["observability/**"]

[deploy]
startCommand = "bun start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "observability"
rootDirectory = "observability"